# -*- coding: utf-8 -*-
# @Author: saitou
# @Date:   2015-06-08 15:41:57
# @Last Modified by:   saitou
# @Last Modified time: 2015-06-08 15:49:56
---
# file: site.yml

- include: dbms.yml

#
# [EOF]
#

